### ISSUE TITLE
Improve fetch regression test

### ISSUE THREAD

**Issue by taldcroft** [sot/eng_archive#108]
The fetch regression test has often had failures that we learn to ignore.  Problems:
- Using the MD5 sum on the ASCII representation of values is prone to platform dependent problems.
- Assuming the MSIDs per content type is static fails when the TDB is updated.

**Comment by jeanconn** [comment]
Should we just remove Ska/engarchive/tests/test_fetch_regr.py or is it sometimes being run manually to good use?

**Comment by jeanconn** [comment]
(I assume this issue speaks to why the test is skipped by default now)

**Comment by taldcroft** [comment]
Yeah, that can be removed.
