### ISSUE TITLE
Error when remotely retrieving DWELL MSID data

### ISSUE THREAD

**Issue by mbaski** [sot/eng_archive#145]
When running test_fetch_regr.py on version 3.43.1 of Ska.engarchive on Windows (accessing data remotely), the error at the bottom of the attached output is generated ("ValueError: assignment destination is read-only" when trying to set "bads" in "_fix_ctu_dwell_mode_bads").

[Ska_Engarchive_bads_write_error.txt](https://github.com/sot/eng_archive/files/2060394/Ska_Engarchive_bads_write_error.txt)

**Comment by jeanconn** [comment]
@taldcroft Do you have advice for debugging remote access?  Can that be run from a Linux installation?

**Comment by jeanconn** [comment]
I see there is an interfacehttps://github.com/sot/eng_archive/blob/94c377a10a79b4f01de56d7db291d50232bcaeea/Ska/engarchive/remote_access.py#L17

**Comment by taldcroft** [comment]
@mbaski @jeanconn - I'll look into this next week.  Maybe there is something obvious.  If not, first I will try to reproduce on linux.  If that fails it would probably make sense for me to sit down with a FOT person on a Windows laptop and try to see what's happening.

**Comment by jeanconn** [comment]
Gotcha.  And yes, I was assuming the 'bads' was just some different data structure when used in a remote access config (a pipe or some such) that couldn't get a write back in this setup, but didn't have experience with using the remote access to debug.

**Comment by mbaski** [comment]
Details for recreating this using remote access on a Linux box on the GRETA network have been sent via direct email to Jean.
