### ISSUE TITLE
fetch returns MSID data with times short of the requested end time even though the data is there

### ISSUE THREAD

**Issue by jzuhone** [sot/eng_archive#222]
Occasionally I notice that the fetched data times can fall well short of the input stop time, even when the data in the archive does extend out past the input stop time. 

```python
from cheta import fetch_sci as fetch

msid = "fptemp_11"
datestart = "2021:189:17:24:06.816"
datestop = "2021:210:01:18:06.816"
stat = '5min'

tlm = fetch.MSID(msid, datestart, datestop, stat=stat)
```
the last value of `tlm.times` corresponds to `2021:210:00:45:18.816`, which is ~33 minutes short of the datestop. 

However, if you run this:

```python
fetch.get_time_range("fptemp_11", format="date")
```
You should be good for a while after `datestop`:

```
('1999:365:19:07:44.395', '2021:210:01:46:52.766')
```

Note that this will only be reproducible today (07/29/31).

**Comment by jzuhone** [comment]
ping @taldcroft @jeanconn

**Comment by jzuhone** [comment]
it appears the reason for this is that there is a gap in the `fptemp_11` data between `2021:210:00:45:18.816` and `2021:210:01:29:02.816` (presumably this is true for the rest of the DEA HKP data)

**Comment by taldcroft** [comment]
Closing this given that there is a gap in ACIS DEA HK telemetry. These gaps are expected, so if a query `stop` time lands in a gap then the returned data will not extend to that `stop` time.
