### ISSUE TITLE
Can't get Msidset with mismatches on shapes of bads?

### ISSUE THREAD

**Issue by jeanconn** [sot/eng_archive#234]
Is it the expected behavior that one will get an error if the "bad" lists for the msids in an Msidset have different lengths / shapes?  

```
In [1]: background_avg_msids = ['ACA00110', 'ACA00326', 'ACA00542', 'ACA00758', 'ACA00974', 'ACA01190', 'ACA01406', 'ACA01622']

In [2]: from cheta import fetch

In [3]: fetch.data_source.set('maude allow_subset=False')

In [4]: fetch.Msidset(background_avg_msids, '2022:001:00:00:00.000', '2022:001:00:01:00.000')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-baa9c512e8c9> in <module>
----> 1 fetch.Msidset(background_avg_msids, '2022:001:00:00:00.000', '2022:001:00:01:00.000')

/proj/sot/ska3/flight/lib/python3.8/site-packages/cheta/fetch.py in __init__(self, msids, start, stop, filter_bad, stat)
   1739 
   1740     def __init__(self, msids, start=LAUNCH_DATE, stop=None, filter_bad=True, stat=None):
-> 1741         super(Msidset, self).__init__(msids, start=start, stop=stop,
   1742                                       filter_bad=filter_bad, stat=stat)
   1743 

/proj/sot/ska3/flight/lib/python3.8/site-packages/cheta/fetch.py in __init__(self, msids, start, stop, filter_bad, stat)
   1469 
   1470         if filter_bad:
-> 1471             self.filter_bad()
   1472 
   1473     def __deepcopy__(self, memo=None):

/proj/sot/ska3/flight/lib/python3.8/site-packages/cheta/fetch.py in filter_bad(self, copy)
   1523                     bads = msid.bads.copy()
   1524                 else:
-> 1525                     bads |= msid.bads
   1526 
   1527             for msid in msids:

ValueError: operands could not be broadcast together with shapes (15,) (29,) (15,) 
```

**Comment by taldcroft** [comment]
Yes that is expected, though I agree this is a bit surprising and makes this class a bit less useful. I haven't run across this because I almost never use it.

In general the right approach is using `MSIDset` followed by `.interpolate()` to get the MSIDs aligned and filtered. E.g.
```
dat = fetch.MSIDset(background_avg_msids, start, stop)
dat.interpolate(times=dat[background_avg_msids[0]].times)
# OR
dat.interpolate(2.05)
```
This will interpolate to a common time sampling and filter bad data.

**Comment by jeanconn** [comment]
Thanks.  And yes, that's about what I figured, though I think that suggests that this question should become a doc issue, as I was surprised to not easily find this as a gotcha in the Msidset.

With regard to interpolation, if working with maude data on the edge of realtime, I had the tiny concern that I didn't want to interpolate immediately when the data might be missing because MAUDE was incomplete.

**Comment by jeanconn** [comment]
These are background avg values so not really same aca image readout depending on the definition of aca image readout.  But it may be the case that it is most straightforward to handle as you suggest.

**Comment by taldcroft** [comment]
Oops, then never mind.

**Comment by taldcroft** [comment]
FYI I have a PR in work to fix this.
